Paramiko Security Update (#167)
* Switching to sdplog (with file-based configuration option via riaps-log.conf in the app's folder) for component code logging. As the signature of logger.{info,warn,err...} has changed it may break existing code. Fix: e.g., logger.info("msg %s %s", arg1, arg2) --> logger.info("msg %s %s" % (arg1,arg2) (#137)

* Logger format updates (tests)

* Add read me file for RIAPS configuration options.

* Develop setuppy (#138)

* Removing duplication of script files (kept scripts/ versions)

* Update version.sh

* Created readme file for riaps_gen, plan to reference this in RIAPS tutorials

* Update log option information

* Include date in log message pattern (#140)

* Include date in log message pattern

* Fix incorrect seconds flag

* Prepare for release

* Add fab commands for updating RIAPS configs (#142)

* Improve sys.put and sys.get (#144)

* Add fab commands for updating RIAPS configs

* Improve sys.put and sys.get

* Formatting adjustment

* Develop sec (#145)

* Introduce security: zmq ec for app comms and ssl ofor deplo/ctrl comms.

* Create readme.md

* App networking isolation based on iptables. depl language is extended, json format modified (breaking change).

* Move new keys for install
Default to BBB interface (only need to change VM and non-BBBs nodes)

* AppArmor profile for riaps_actor -- likely needs more refinements.

* Update home.riaps.workspace.RIAPS.src.scripts.riaps_actor

* Change apparmor config file name and variables within to match RIAPS installation locations

* Installation updates for security and moved conf location to /etc/riaps (instead of /etc)

* Updating installation to use conffiles for configuration management (still testing)

* Clean removal of riaps-pycom

* Add riaps_gen_cert to installation

* fix: riaps_gen_cert - riaps-sys.cert did not move to -o indicated directory

* Create home.riaps.workspace.RIAPS.src.scripts.riaps_actor

Apparmor file for RIAPS Platform development use

* Fix glang 1dev dlog (#149)

* Fixes: lang changes for groups (see Group test), app w/ 1 device (no comp, see Device test), logging in devices.

* Word fix

* fix: stdout logging for device components.

* Install fabfile with riaps-pycom (#146)

* Install fabfile

* Fix installation location and config formatting

* Move install location

* Create riaps-hosts.conf and use RIAPS SSH key

* Add missing new line

* Add missing section header

* Fix riaps-hosts.conf parsing

* Remove extra print

* Create updateKey task to rekey BBBs

* Create sys.hosts command

* Move fabfile into RIAPS package - allows user to have different fabfile

* Move setup_cython fab cmd to sys.py

* Formatting user feedback for consistency

* Security updates for fabfile and rekeying

* BBB rekeying fabfile updates

* Set NIC name for VM to match downloadable VM interface

* put private key on BBB for ctrl communication

* Updated bbb rekeying based on testing

* fab wants absolute paths

* Added command line argument supplying alternate hosts (#151)

* Added optional 'riaps-hosts.conf' flag

Usage: -f <absolute path to riaps-hosts.conf>

* Fixed how arguments are passed to subprocess

* fixed variable check, added error message

* Fixed argument check

* Prep for new release

* Update README.md

* Formatting update

* Document update

* Readme updates

* Adjust help on riaps-hosts.conf file format

* Dev sec certs (#156)

* Adjust readme help to match current hostfile format (#154)

* Switching to sdplog (with file-based configuration option via riaps-log.conf in the app's folder) for component code logging. As the signature of logger.{info,warn,err...} has changed it may break existing code. Fix: e.g., logger.info("msg %s %s", arg1, arg2) --> logger.info("msg %s %s" % (arg1,arg2) (#137)

* Logger format updates (tests)

* Add read me file for RIAPS configuration options.

* Develop setuppy (#138)

* Removing duplication of script files (kept scripts/ versions)

* Update version.sh

* Created readme file for riaps_gen, plan to reference this in RIAPS tutorials

* Update log option information

* Include date in log message pattern (#140)

* Include date in log message pattern

* Fix incorrect seconds flag

* Prepare for release

* Add fab commands for updating RIAPS configs (#142)

* Improve sys.put and sys.get (#144)

* Add fab commands for updating RIAPS configs

* Improve sys.put and sys.get

* Formatting adjustment

* Develop sec (#145)

* Introduce security: zmq ec for app comms and ssl ofor deplo/ctrl comms.

* Create readme.md

* App networking isolation based on iptables. depl language is extended, json format modified (breaking change).

* Move new keys for install
Default to BBB interface (only need to change VM and non-BBBs nodes)

* AppArmor profile for riaps_actor -- likely needs more refinements.

* Update home.riaps.workspace.RIAPS.src.scripts.riaps_actor

* Change apparmor config file name and variables within to match RIAPS installation locations

* Installation updates for security and moved conf location to /etc/riaps (instead of /etc)

* Updating installation to use conffiles for configuration management (still testing)

* Clean removal of riaps-pycom

* Add riaps_gen_cert to installation

* fix: riaps_gen_cert - riaps-sys.cert did not move to -o indicated directory

* Create home.riaps.workspace.RIAPS.src.scripts.riaps_actor

Apparmor file for RIAPS Platform development use

* Fix glang 1dev dlog (#149)

* Fixes: lang changes for groups (see Group test), app w/ 1 device (no comp, see Device test), logging in devices.

* Word fix

* fix: stdout logging for device components.

* Install fabfile with riaps-pycom (#146)

* Install fabfile

* Fix installation location and config formatting

* Move install location

* Create riaps-hosts.conf and use RIAPS SSH key

* Add missing new line

* Add missing section header

* Fix riaps-hosts.conf parsing

* Remove extra print

* Create updateKey task to rekey BBBs

* Create sys.hosts command

* Move fabfile into RIAPS package - allows user to have different fabfile

* Move setup_cython fab cmd to sys.py

* Formatting user feedback for consistency

* Security updates for fabfile and rekeying

* BBB rekeying fabfile updates

* Set NIC name for VM to match downloadable VM interface

* put private key on BBB for ctrl communication

* Updated bbb rekeying based on testing

* fab wants absolute paths

* Added command line argument supplying alternate hosts (#151)

* Added optional 'riaps-hosts.conf' flag

Usage: -f <absolute path to riaps-hosts.conf>

* Fixed how arguments are passed to subprocess

* fixed variable check, added error message

* Fixed argument check

* Prep for new release

* Update README.md

* Formatting update

* Document update

* Readme updates

* Adjust help on riaps-hosts.conf file format

* Add private key identification to allow communication with RIAPS hosts looking to join the rekeyed environment

* Correct all paths

* Efficiency update

* Added requirement for certificate use in ssl connection

* Expand expiration date to 3 years

* Update expired certificate

* Update privileges to be an executable like all the other scripts

* parse cpp args (#159)

* riaps-sys.cert file permissions should be set to 444

* Add comment to indicate time units expected

* Minor fix: device components to support the same API (for ID-s) as a normal component.

* Take out groups for now.

* Moved comments to their own lines - seemed to be interfering with profile building

* Changes to address apparmor problems. New Python package required: apparmor_monkeys

* Minor fixes: duplicate app names are rejected, EC certs are validated upon actor start.

* Updated apparmor file for installed riaps-pycom and make it arch dependent

* Added riaps-externals directory to profile

* Add /usr/local/riaps/keys files to conffiles control

* Update version.sh

* Update version.sh

* Fixes to some security-induced issues.

* Update version.sh

* fix: timeout on p2p responses caused a mistaken removal of a peer from the group. The correct remedy is to increase the p2p timeouts.

* Exception error thrown, print statement has too many elements.

* Remove riaps-systemd package (move to riaps-pycom)
Add securityOn, securityOff, flushIPTables fabric commands

* Adjust package location of default keys

* Update version.sh

* Organized package release material (riaps-systemd package now gone)

* Fix hostname file install and fabfile edit issue

* Change to sphinx doc building process: now sphix-apidoc is run first.

* Create .readthedocs.yaml

* Update conf.py

* Requirements for building the docs.

* Update .readthedocs.yaml

* Update requirements.txt

* Update requirements.txt

* Update requirements.txt

* Update requirements.txt

* Update requirements.txt

* Update requirements.txt

* Sphinx configuration: conf.py for local build, conf_rtd.py readthedocs build.

* Update to the readthedocs control file.

* Adjustments to doc generation process

* Update conf_rtd.py

* Update conf.py

* Update conf.py

* Cleanup rtd related files.

* More cleanup for rtd - local build and rtd build now produces the same result.

* Table resetConfig fab function for now, reevaluate function for next release

* Fix inside port handlers, logging package in python, handler case issues (#164)

* fix: import spdlog instead of logging

* fix: case issue

* fix: handelrs for inside ports

* fix: handelrs for inside ports

* Error message on  port again exception



Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/riaps/run/port.py", line 294, in port_send
    self.socket.send_multipart(sendMsg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/sugar/socket.py", line 439, in send_multipart
    return self.send(msg_parts[-1], flags, copy=copy, track=track)
  File "/usr/local/lib/python3.6/dist-packages/zmq/sugar/socket.py", line 392, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 725, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 786, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 212, in zmq.backend.cython.socket._send_frame
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

During handling of the above exception, another exception occurred:
Received the following message when a request/reply was not fully ready.  Application still ran, but provided clues to this TypeError.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/riaps/run/comp.py", line 166, in run
    func_()
  File "/home/riaps/riaps_apps/DistributedEstimator/LocalEstimator.py", line 30, in on_ready
    if self.query.send_pyobj(msg):
  File "/usr/local/lib/python3.6/dist-packages/riaps/run/reqPort.py", line 84, in send_pyobj
    return self.port_send(msg,True)
  File "/usr/local/lib/python3.6/dist-packages/riaps/run/port.py", line 296, in port_send
    raise PortError("send error (%d)" % e.errno) from e
TypeError: __init__() missing 1 required positional argument: 'errno'

* Place all config files in /etc/riaps and soft link to /usr/local/riaps/ appropriately (etc and keys)

* Prep for 1.1.16 release

* Install conf file location adjustment

* Refining installation

* Fix riaps configuration and keys path reference to be /etc/riaps/
Remove riaps-systemd from list of riaps packages

* Need to execute fab routines with a routine

* Directory adjustment

* Update paramiko to 2.6.0 per security issue found on github pull request (https://github.com/RIAPS/riaps-pycom/network/alert/doc/source/requirements.txt/paramiko/open)