Error message on  port again exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/riaps/run/port.py", line 294, in port_send
    self.socket.send_multipart(sendMsg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/sugar/socket.py", line 439, in send_multipart
    return self.send(msg_parts[-1], flags, copy=copy, track=track)
  File "/usr/local/lib/python3.6/dist-packages/zmq/sugar/socket.py", line 392, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 725, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 786, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 212, in zmq.backend.cython.socket._send_frame
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

During handling of the above exception, another exception occurred:
Received the following message when a request/reply was not fully ready.  Application still ran, but provided clues to this TypeError.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/riaps/run/comp.py", line 166, in run
    func_()
  File "/home/riaps/riaps_apps/DistributedEstimator/LocalEstimator.py", line 30, in on_ready
    if self.query.send_pyobj(msg):
  File "/usr/local/lib/python3.6/dist-packages/riaps/run/reqPort.py", line 84, in send_pyobj
    return self.port_send(msg,True)
  File "/usr/local/lib/python3.6/dist-packages/riaps/run/port.py", line 296, in port_send
    raise PortError("send error (%d)" % e.errno) from e
TypeError: __init__() missing 1 required positional argument: 'errno'